[[coreutils]]
arch = "aarch64"
git-tree-sha1 = "b0c1b3ce14f91b9690bc14faaf28f63f2d294bce"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "c774d816b7260fa7ad4021321e52c0b40dbb0eacb16bb0226227591b83b9efd4"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.aarch64-linux-gnu.tar.gz"
[[coreutils]]
arch = "aarch64"
git-tree-sha1 = "37d87b77420ef1ab4b4d9181e2599328bb5d4eeb"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "b856f1320a8b6c20832937709f7baa80383be6cda575891dca2b5245354df2b1"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.aarch64-linux-musl.tar.gz"
[[coreutils]]
arch = "aarch64"
git-tree-sha1 = "a58503af18c2dc778ed79becda78a3ff2b44abe5"
os = "freebsd"

    [[coreutils.download]]
    sha256 = "2ef60d1a09ea35c1e97599566e9ad0eb3339722f30b4749f2edc19be8cb24a02"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.aarch64-unknown-freebsd.tar.gz"
[[coreutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3eb8eeb39b427a62061fc1902bc07ed2285f3c44"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "6857507ae300ec667f99981e312e63b3305966874fbe9a821cf94a417638a39a"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.armv6l-linux-gnueabihf.tar.gz"
[[coreutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8c9348d1c669a258d346877d51b9975ded5a6185"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "85cab6a4235bbf836424c86795951a75cdd238a501a786507c4a89aed4de1714"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.armv6l-linux-musleabihf.tar.gz"
[[coreutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "59fbb3061dab0af1e1eb1354c3443df71a305aa3"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "6c2cb5d647f1b342539734d6f72dc5c79d26861abff46411f9321f1a40d99399"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.armv7l-linux-gnueabihf.tar.gz"
[[coreutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e376aadc9649c054147220d9f31cc070752d0359"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "1e3719a0eddd04014459508f2034026748c8b9745d4054c04259dc15f6545545"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.armv7l-linux-musleabihf.tar.gz"
[[coreutils]]
arch = "i686"
git-tree-sha1 = "22fd63e34f450eefca2dc280c1de28aefa35546b"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "282287e044ba8aa85e5c64a942fa85b6ca89524b7c7a67585d11074c3f76f5c9"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.i686-linux-gnu.tar.gz"
[[coreutils]]
arch = "i686"
git-tree-sha1 = "2208aee99a2673eb83c48a4ecd46e2bd4c2700d3"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "4772c9b98d48a8f1e725d443d04fb94e428cfa3f4d6828266ee3bba86bf915ad"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.i686-linux-musl.tar.gz"
[[coreutils]]
arch = "powerpc64le"
git-tree-sha1 = "e83ad110efa2310f831fa7e8fbb22decc3d39749"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "ef4a3b717926b3eb2a4a053199203188b1ea287e16e67e771dd57bb793176646"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.powerpc64le-linux-gnu.tar.gz"
[[coreutils]]
arch = "riscv64"
git-tree-sha1 = "710973a1e8fd7b41c1963b25289d465e796ef670"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "863ecdbd4bf20f84a84a3183621eace7caf156599b7f7ceddec85516b00ef94c"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.riscv64-linux-gnu.tar.gz"
[[coreutils]]
arch = "x86_64"
git-tree-sha1 = "b4f58f884773ede28f114adcb5d58c29ece1ce46"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "665c8c3347ec009c47d7abcc8ad7a344997ceec77d2945b71d8c156b072c2a1a"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.x86_64-linux-gnu.tar.gz"
[[coreutils]]
arch = "x86_64"
git-tree-sha1 = "f818499d121bb6ec3678d747fa169c1deabed9ca"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "a4e56074e5257bc7ae3a58c5994f9e48fdb8cfa82e131284453ddd60d3ed4486"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.x86_64-linux-musl.tar.gz"
[[coreutils]]
arch = "x86_64"
git-tree-sha1 = "f1cac878a1554507f28d338c27775cf1ecc50a67"
os = "freebsd"

    [[coreutils.download]]
    sha256 = "168c41092f4fe77319da9a461d18a8a15c604ba26e31e8a363cd4e46003b508d"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.11.0+0/coreutils.v9.11.0.x86_64-unknown-freebsd.tar.gz"
