[[coreutils]]
arch = "aarch64"
git-tree-sha1 = "71c8d74a437c09f03324dd6761ec71eabd56ce5d"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "50f7041855fb5f4e22486d8dc5a15361be7407351a82cde8c4eb313105edfda3"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.aarch64-linux-gnu.tar.gz"
[[coreutils]]
arch = "aarch64"
git-tree-sha1 = "831d2f0ac928a7ce29b2cec5307276ec91b775b2"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "23c08524a8a00a6b691c5fdf3afba871b3db046a50a64ca27b684603e7d7c65b"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.aarch64-linux-musl.tar.gz"
[[coreutils]]
arch = "aarch64"
git-tree-sha1 = "ed0958e0f8007f8296a76c5c82cb51bad9ea7a05"
os = "freebsd"

    [[coreutils.download]]
    sha256 = "5a1c7817fac8876d6bcc2b4696dee1d3cd1eec4b7ad69193cebd555a3a4ff8fa"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.aarch64-unknown-freebsd.tar.gz"
[[coreutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "df40f9beb27890f67ec023edad80388a66a98cc8"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "ae38fbd20cfc9bc9810a88c461c5c0f4afebfb98caee5a9bfbb66c827def3494"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.armv6l-linux-gnueabihf.tar.gz"
[[coreutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24b98388b86a4bc700296ec4f7670ebe66a91ab8"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "388395f4122ac4bd806d67d932373e35d01b6f206625eb75ac3f3cfc6d874e36"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.armv6l-linux-musleabihf.tar.gz"
[[coreutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fa94f4d749464232ca6e12fb745446dbcba4ca9d"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "94921648a950519ebb563a53c6cbd7da303b5fda17b40e045f6266367d492cfd"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.armv7l-linux-gnueabihf.tar.gz"
[[coreutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "edf1d82fdbc5845f06128ebe245fdca171c62630"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "5f7b233e4f66065c10f961debf85d37a138eb2cb6b8009de841aea620282ec12"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.armv7l-linux-musleabihf.tar.gz"
[[coreutils]]
arch = "i686"
git-tree-sha1 = "81a5dce7446bd3b8c3a71b99b9bc0bd4f95201ca"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "cf4e46ee712ea4bf79954ad8f6ebc2e926c59cc2a7d123c7ed31a7990e4ac575"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.i686-linux-gnu.tar.gz"
[[coreutils]]
arch = "i686"
git-tree-sha1 = "917811ce2f90fdff863bdb7257aa652580ce4a06"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "7f54ce88df7b10c168a3395a9568ec3b89a6b64813eb2f742ba8f07e2e042e2c"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.i686-linux-musl.tar.gz"
[[coreutils]]
arch = "powerpc64le"
git-tree-sha1 = "9e2e9a9a7a344b8512d1bd063e01d094ebc0101f"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "23717e41fc24e33caf329bc0dbe85f6621677a251b04b1ae33f76742e534e426"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.powerpc64le-linux-gnu.tar.gz"
[[coreutils]]
arch = "riscv64"
git-tree-sha1 = "d57892ae4ad4eb946789c0439975cab389abac93"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "0cbedc47c4e27e05f5c063cd50496b762927f0736d46ebf7719059102ce4b753"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.riscv64-linux-gnu.tar.gz"
[[coreutils]]
arch = "x86_64"
git-tree-sha1 = "79ac739243572699a9f1b5ac4c987806a7015e7d"
libc = "glibc"
os = "linux"

    [[coreutils.download]]
    sha256 = "1f674d93c01549fa9dd2294a97ad5a9071de72cdf35849f9ff32fbc6747237d3"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.x86_64-linux-gnu.tar.gz"
[[coreutils]]
arch = "x86_64"
git-tree-sha1 = "a45ac47dd1e8b833b92ad50960a43159cf693158"
libc = "musl"
os = "linux"

    [[coreutils.download]]
    sha256 = "51d2642759aebc0c43c8aaa9455be2d22abaf89dcf463009b959885c0bfcf069"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.x86_64-linux-musl.tar.gz"
[[coreutils]]
arch = "x86_64"
git-tree-sha1 = "f0ab5d4193ed3735797040b73d2a42d83b9d06d5"
os = "freebsd"

    [[coreutils.download]]
    sha256 = "9f2b01b54d3af4628f802609869f7df75fc63d280dcc689cce0ddbeeda46808f"
    url = "https://github.com/JuliaBinaryWrappers/coreutils_jll.jl/releases/download/coreutils-v9.10.0+0/coreutils.v9.10.0.x86_64-unknown-freebsd.tar.gz"
