# Autogenerated wrapper script for coreutils_jll for riscv64-linux-gnu
export b2sum, base32, base64, basename_bin, basenc, cat_bin, chcon, chgrp, chmod_bin, chown_bin, chroot, cksum, comm, cp_bin, csplit, cut, date, dd, df, dir, dircolors, dirname_bin, du, echo, env, expand, expr, factor, false_bin, fmt, fold, groups, head, hostid, id, install, join_bin, kill_bin, left_bracket, libstdbuf, link, ln, logname, ls, md5sum, mkdir_bin, mkfifo, mknod, mktemp_bin, mv_bin, nice, nl, nohup, nproc, numfmt, od, paste, pathchk, pinky, pr, printenv, printf, ptx, pwd_bin, readlink_bin, realpath_bin, rm_bin, rmdir, runcon, seq, sha1sum, sha224sum, sha256sum, sha384sum, sha512sum, shred, shuf, sleep_bin, sort_bin, split_bin, stat_bin, stdbuf, stty, sum_bin, sync, tac, tail_bin, tee, test, timeout, touch_bin, tr, true_bin, truncate_bin, tsort, tty, uname, unexpand, uniq, unlink_bin, uptime, users, vdir, wc, who, whoami, yes

JLLWrappers.@generate_wrapper_header("coreutils")
JLLWrappers.@declare_library_product(libstdbuf, "libstdbuf.so")
JLLWrappers.@declare_executable_product(b2sum)
JLLWrappers.@declare_executable_product(base32)
JLLWrappers.@declare_executable_product(base64)
JLLWrappers.@declare_executable_product(basename_bin)
JLLWrappers.@declare_executable_product(basenc)
JLLWrappers.@declare_executable_product(cat_bin)
JLLWrappers.@declare_executable_product(chcon)
JLLWrappers.@declare_executable_product(chgrp)
JLLWrappers.@declare_executable_product(chmod_bin)
JLLWrappers.@declare_executable_product(chown_bin)
JLLWrappers.@declare_executable_product(chroot)
JLLWrappers.@declare_executable_product(cksum)
JLLWrappers.@declare_executable_product(comm)
JLLWrappers.@declare_executable_product(cp_bin)
JLLWrappers.@declare_executable_product(csplit)
JLLWrappers.@declare_executable_product(cut)
JLLWrappers.@declare_executable_product(date)
JLLWrappers.@declare_executable_product(dd)
JLLWrappers.@declare_executable_product(df)
JLLWrappers.@declare_executable_product(dir)
JLLWrappers.@declare_executable_product(dircolors)
JLLWrappers.@declare_executable_product(dirname_bin)
JLLWrappers.@declare_executable_product(du)
JLLWrappers.@declare_executable_product(echo)
JLLWrappers.@declare_executable_product(env)
JLLWrappers.@declare_executable_product(expand)
JLLWrappers.@declare_executable_product(expr)
JLLWrappers.@declare_executable_product(factor)
JLLWrappers.@declare_executable_product(false_bin)
JLLWrappers.@declare_executable_product(fmt)
JLLWrappers.@declare_executable_product(fold)
JLLWrappers.@declare_executable_product(groups)
JLLWrappers.@declare_executable_product(head)
JLLWrappers.@declare_executable_product(hostid)
JLLWrappers.@declare_executable_product(id)
JLLWrappers.@declare_executable_product(install)
JLLWrappers.@declare_executable_product(join_bin)
JLLWrappers.@declare_executable_product(kill_bin)
JLLWrappers.@declare_executable_product(left_bracket)
JLLWrappers.@declare_executable_product(link)
JLLWrappers.@declare_executable_product(ln)
JLLWrappers.@declare_executable_product(logname)
JLLWrappers.@declare_executable_product(ls)
JLLWrappers.@declare_executable_product(md5sum)
JLLWrappers.@declare_executable_product(mkdir_bin)
JLLWrappers.@declare_executable_product(mkfifo)
JLLWrappers.@declare_executable_product(mknod)
JLLWrappers.@declare_executable_product(mktemp_bin)
JLLWrappers.@declare_executable_product(mv_bin)
JLLWrappers.@declare_executable_product(nice)
JLLWrappers.@declare_executable_product(nl)
JLLWrappers.@declare_executable_product(nohup)
JLLWrappers.@declare_executable_product(nproc)
JLLWrappers.@declare_executable_product(numfmt)
JLLWrappers.@declare_executable_product(od)
JLLWrappers.@declare_executable_product(paste)
JLLWrappers.@declare_executable_product(pathchk)
JLLWrappers.@declare_executable_product(pinky)
JLLWrappers.@declare_executable_product(pr)
JLLWrappers.@declare_executable_product(printenv)
JLLWrappers.@declare_executable_product(printf)
JLLWrappers.@declare_executable_product(ptx)
JLLWrappers.@declare_executable_product(pwd_bin)
JLLWrappers.@declare_executable_product(readlink_bin)
JLLWrappers.@declare_executable_product(realpath_bin)
JLLWrappers.@declare_executable_product(rm_bin)
JLLWrappers.@declare_executable_product(rmdir)
JLLWrappers.@declare_executable_product(runcon)
JLLWrappers.@declare_executable_product(seq)
JLLWrappers.@declare_executable_product(sha1sum)
JLLWrappers.@declare_executable_product(sha224sum)
JLLWrappers.@declare_executable_product(sha256sum)
JLLWrappers.@declare_executable_product(sha384sum)
JLLWrappers.@declare_executable_product(sha512sum)
JLLWrappers.@declare_executable_product(shred)
JLLWrappers.@declare_executable_product(shuf)
JLLWrappers.@declare_executable_product(sleep_bin)
JLLWrappers.@declare_executable_product(sort_bin)
JLLWrappers.@declare_executable_product(split_bin)
JLLWrappers.@declare_executable_product(stat_bin)
JLLWrappers.@declare_executable_product(stdbuf)
JLLWrappers.@declare_executable_product(stty)
JLLWrappers.@declare_executable_product(sum_bin)
JLLWrappers.@declare_executable_product(sync)
JLLWrappers.@declare_executable_product(tac)
JLLWrappers.@declare_executable_product(tail_bin)
JLLWrappers.@declare_executable_product(tee)
JLLWrappers.@declare_executable_product(test)
JLLWrappers.@declare_executable_product(timeout)
JLLWrappers.@declare_executable_product(touch_bin)
JLLWrappers.@declare_executable_product(tr)
JLLWrappers.@declare_executable_product(true_bin)
JLLWrappers.@declare_executable_product(truncate_bin)
JLLWrappers.@declare_executable_product(tsort)
JLLWrappers.@declare_executable_product(tty)
JLLWrappers.@declare_executable_product(uname)
JLLWrappers.@declare_executable_product(unexpand)
JLLWrappers.@declare_executable_product(uniq)
JLLWrappers.@declare_executable_product(unlink_bin)
JLLWrappers.@declare_executable_product(uptime)
JLLWrappers.@declare_executable_product(users)
JLLWrappers.@declare_executable_product(vdir)
JLLWrappers.@declare_executable_product(wc)
JLLWrappers.@declare_executable_product(who)
JLLWrappers.@declare_executable_product(whoami)
JLLWrappers.@declare_executable_product(yes)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libstdbuf,
        "libexec/coreutils/libstdbuf.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        b2sum,
        "bin/b2sum",
    )

    JLLWrappers.@init_executable_product(
        base32,
        "bin/base32",
    )

    JLLWrappers.@init_executable_product(
        base64,
        "bin/base64",
    )

    JLLWrappers.@init_executable_product(
        basename_bin,
        "bin/basename",
    )

    JLLWrappers.@init_executable_product(
        basenc,
        "bin/basenc",
    )

    JLLWrappers.@init_executable_product(
        cat_bin,
        "bin/cat",
    )

    JLLWrappers.@init_executable_product(
        chcon,
        "bin/chcon",
    )

    JLLWrappers.@init_executable_product(
        chgrp,
        "bin/chgrp",
    )

    JLLWrappers.@init_executable_product(
        chmod_bin,
        "bin/chmod",
    )

    JLLWrappers.@init_executable_product(
        chown_bin,
        "bin/chown",
    )

    JLLWrappers.@init_executable_product(
        chroot,
        "bin/chroot",
    )

    JLLWrappers.@init_executable_product(
        cksum,
        "bin/cksum",
    )

    JLLWrappers.@init_executable_product(
        comm,
        "bin/comm",
    )

    JLLWrappers.@init_executable_product(
        cp_bin,
        "bin/cp",
    )

    JLLWrappers.@init_executable_product(
        csplit,
        "bin/csplit",
    )

    JLLWrappers.@init_executable_product(
        cut,
        "bin/cut",
    )

    JLLWrappers.@init_executable_product(
        date,
        "bin/date",
    )

    JLLWrappers.@init_executable_product(
        dd,
        "bin/dd",
    )

    JLLWrappers.@init_executable_product(
        df,
        "bin/df",
    )

    JLLWrappers.@init_executable_product(
        dir,
        "bin/dir",
    )

    JLLWrappers.@init_executable_product(
        dircolors,
        "bin/dircolors",
    )

    JLLWrappers.@init_executable_product(
        dirname_bin,
        "bin/dirname",
    )

    JLLWrappers.@init_executable_product(
        du,
        "bin/du",
    )

    JLLWrappers.@init_executable_product(
        echo,
        "bin/echo",
    )

    JLLWrappers.@init_executable_product(
        env,
        "bin/env",
    )

    JLLWrappers.@init_executable_product(
        expand,
        "bin/expand",
    )

    JLLWrappers.@init_executable_product(
        expr,
        "bin/expr",
    )

    JLLWrappers.@init_executable_product(
        factor,
        "bin/factor",
    )

    JLLWrappers.@init_executable_product(
        false_bin,
        "bin/false",
    )

    JLLWrappers.@init_executable_product(
        fmt,
        "bin/fmt",
    )

    JLLWrappers.@init_executable_product(
        fold,
        "bin/fold",
    )

    JLLWrappers.@init_executable_product(
        groups,
        "bin/groups",
    )

    JLLWrappers.@init_executable_product(
        head,
        "bin/head",
    )

    JLLWrappers.@init_executable_product(
        hostid,
        "bin/hostid",
    )

    JLLWrappers.@init_executable_product(
        id,
        "bin/id",
    )

    JLLWrappers.@init_executable_product(
        install,
        "bin/install",
    )

    JLLWrappers.@init_executable_product(
        join_bin,
        "bin/join",
    )

    JLLWrappers.@init_executable_product(
        kill_bin,
        "bin/kill",
    )

    JLLWrappers.@init_executable_product(
        left_bracket,
        "bin/[",
    )

    JLLWrappers.@init_executable_product(
        link,
        "bin/link",
    )

    JLLWrappers.@init_executable_product(
        ln,
        "bin/ln",
    )

    JLLWrappers.@init_executable_product(
        logname,
        "bin/logname",
    )

    JLLWrappers.@init_executable_product(
        ls,
        "bin/ls",
    )

    JLLWrappers.@init_executable_product(
        md5sum,
        "bin/md5sum",
    )

    JLLWrappers.@init_executable_product(
        mkdir_bin,
        "bin/mkdir",
    )

    JLLWrappers.@init_executable_product(
        mkfifo,
        "bin/mkfifo",
    )

    JLLWrappers.@init_executable_product(
        mknod,
        "bin/mknod",
    )

    JLLWrappers.@init_executable_product(
        mktemp_bin,
        "bin/mktemp",
    )

    JLLWrappers.@init_executable_product(
        mv_bin,
        "bin/mv",
    )

    JLLWrappers.@init_executable_product(
        nice,
        "bin/nice",
    )

    JLLWrappers.@init_executable_product(
        nl,
        "bin/nl",
    )

    JLLWrappers.@init_executable_product(
        nohup,
        "bin/nohup",
    )

    JLLWrappers.@init_executable_product(
        nproc,
        "bin/nproc",
    )

    JLLWrappers.@init_executable_product(
        numfmt,
        "bin/numfmt",
    )

    JLLWrappers.@init_executable_product(
        od,
        "bin/od",
    )

    JLLWrappers.@init_executable_product(
        paste,
        "bin/paste",
    )

    JLLWrappers.@init_executable_product(
        pathchk,
        "bin/pathchk",
    )

    JLLWrappers.@init_executable_product(
        pinky,
        "bin/pinky",
    )

    JLLWrappers.@init_executable_product(
        pr,
        "bin/pr",
    )

    JLLWrappers.@init_executable_product(
        printenv,
        "bin/printenv",
    )

    JLLWrappers.@init_executable_product(
        printf,
        "bin/printf",
    )

    JLLWrappers.@init_executable_product(
        ptx,
        "bin/ptx",
    )

    JLLWrappers.@init_executable_product(
        pwd_bin,
        "bin/pwd",
    )

    JLLWrappers.@init_executable_product(
        readlink_bin,
        "bin/readlink",
    )

    JLLWrappers.@init_executable_product(
        realpath_bin,
        "bin/realpath",
    )

    JLLWrappers.@init_executable_product(
        rm_bin,
        "bin/rm",
    )

    JLLWrappers.@init_executable_product(
        rmdir,
        "bin/rmdir",
    )

    JLLWrappers.@init_executable_product(
        runcon,
        "bin/runcon",
    )

    JLLWrappers.@init_executable_product(
        seq,
        "bin/seq",
    )

    JLLWrappers.@init_executable_product(
        sha1sum,
        "bin/sha1sum",
    )

    JLLWrappers.@init_executable_product(
        sha224sum,
        "bin/sha224sum",
    )

    JLLWrappers.@init_executable_product(
        sha256sum,
        "bin/sha256sum",
    )

    JLLWrappers.@init_executable_product(
        sha384sum,
        "bin/sha384sum",
    )

    JLLWrappers.@init_executable_product(
        sha512sum,
        "bin/sha512sum",
    )

    JLLWrappers.@init_executable_product(
        shred,
        "bin/shred",
    )

    JLLWrappers.@init_executable_product(
        shuf,
        "bin/shuf",
    )

    JLLWrappers.@init_executable_product(
        sleep_bin,
        "bin/sleep",
    )

    JLLWrappers.@init_executable_product(
        sort_bin,
        "bin/sort",
    )

    JLLWrappers.@init_executable_product(
        split_bin,
        "bin/split",
    )

    JLLWrappers.@init_executable_product(
        stat_bin,
        "bin/stat",
    )

    JLLWrappers.@init_executable_product(
        stdbuf,
        "bin/stdbuf",
    )

    JLLWrappers.@init_executable_product(
        stty,
        "bin/stty",
    )

    JLLWrappers.@init_executable_product(
        sum_bin,
        "bin/sum",
    )

    JLLWrappers.@init_executable_product(
        sync,
        "bin/sync",
    )

    JLLWrappers.@init_executable_product(
        tac,
        "bin/tac",
    )

    JLLWrappers.@init_executable_product(
        tail_bin,
        "bin/tail",
    )

    JLLWrappers.@init_executable_product(
        tee,
        "bin/tee",
    )

    JLLWrappers.@init_executable_product(
        test,
        "bin/test",
    )

    JLLWrappers.@init_executable_product(
        timeout,
        "bin/timeout",
    )

    JLLWrappers.@init_executable_product(
        touch_bin,
        "bin/touch",
    )

    JLLWrappers.@init_executable_product(
        tr,
        "bin/tr",
    )

    JLLWrappers.@init_executable_product(
        true_bin,
        "bin/true",
    )

    JLLWrappers.@init_executable_product(
        truncate_bin,
        "bin/truncate",
    )

    JLLWrappers.@init_executable_product(
        tsort,
        "bin/tsort",
    )

    JLLWrappers.@init_executable_product(
        tty,
        "bin/tty",
    )

    JLLWrappers.@init_executable_product(
        uname,
        "bin/uname",
    )

    JLLWrappers.@init_executable_product(
        unexpand,
        "bin/unexpand",
    )

    JLLWrappers.@init_executable_product(
        uniq,
        "bin/uniq",
    )

    JLLWrappers.@init_executable_product(
        unlink_bin,
        "bin/unlink",
    )

    JLLWrappers.@init_executable_product(
        uptime,
        "bin/uptime",
    )

    JLLWrappers.@init_executable_product(
        users,
        "bin/users",
    )

    JLLWrappers.@init_executable_product(
        vdir,
        "bin/vdir",
    )

    JLLWrappers.@init_executable_product(
        wc,
        "bin/wc",
    )

    JLLWrappers.@init_executable_product(
        who,
        "bin/who",
    )

    JLLWrappers.@init_executable_product(
        whoami,
        "bin/whoami",
    )

    JLLWrappers.@init_executable_product(
        yes,
        "bin/yes",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
